export const ROUTES = {
  HOME: '/',
  PROCEDURES: '/procedures',
  PROCEDURE_DETAIL: (id: string) => `/procedures/${id}`,
  ABOUT: '/about',
  REVIEWS: '/reviews',
  CONTACTS: '/contacts',
  PRIVACY: '/privacy',
  CONTACTS_WITH_PROCEDURE: (procedureId: string) => `/contacts?procedureId=${procedureId}`,
  ADMIN_LOGIN: '/admin/login',
  ADMIN: '/admin',
  ADMIN_PROCEDURES: '/admin/procedures',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_CONTACTS: '/admin/contacts',
  ADMIN_ABOUT: '/admin/about',
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_CLIENTS: '/admin/clients',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_CLIENT_HISTORY: (clientId: string) => `/admin/clients/${clientId}`,
} as const

